### ISSUE TITLE
Instance not undeployed when removed from project

### ISSUE THREAD

**Issue by rjhowe** [tiwillia/OpenShift_Lab_Automation#15]
Problem Recreation Steps 
-Instance is Deployed
-While Deployed it is removed from project
-Add new instance with the same IP 
-Deploy instance
-Instance never spins up

I was able to see the old instance was still up in the Open Stack environment. 

FIx: 
I would think adding the undeploy instance call when removing from project

**Comment by rjhowe** [comment]
NVM should of read past submitted issues

**Comment by tiwillia** [comment]
https://github.com/tiwillia/OpenShift_Lab_Automation/issues/8
